### ISSUE TITLE
Plugin and Ardour4 from Ubuntu 16.04 repository lock up together

### ISSUE THREAD

**Issue by lucaspcamargo** [x42/avldrums.lv2#1]
This happens with the latest version, compiled with the lv2-dev package and distribution development packages

**Comment by x42** [comment]
This is most likely a bug with Ubuntu, Ardour4 and/or your specific system.

I cannot reproduce this on debian and others report it works on Ubuntu 16.04 with Ardour 5.

Please try to reproduce this with Ardour5 (preferably 5.12 from ardour.org) and binaries from  http://x42-plugins.com/x42/x42-avldrums

**Comment by x42** [comment]
No other user has reported this, and there's no backtrace nor a recipe hoe to reproduce this issue.

If it is still an issue to you, please re-report, ideally with a backtrace or instructions how to reproduce this.
