### ISSUE TITLE
Image association with the note

### ISSUE THREAD

**Issue by iurienistor** [x42/avldrums.lv2#10]
I think it would be useful in the GUI images when pressing something to see for which note is mapped, something like: Snare Edge (E2), Closed Hit-hat (F2#). It would be easier to find the instruments when MIDI editing.

**Comment by x42** [comment]
I suppose I could add that. I don't see how this helps when editing though. One does not usually have the plugin-ui visible for that.

The plugin includes a built-in midnam file, and a LV2 extension to inform a LV2 host about the mapping. When editing, this allows to directly shows the note-names on the timeline. No user action is needed for that:

![avldrum-midnam](https://user-images.githubusercontent.com/30246/65278718-f9f2e580-db2c-11e9-81dc-1feee8fcf0b5.png)

**Comment by iurienistor** [comment]
The use case is for beginners like me. It would be easy to learn the instrument, because names don't tell me much how instrument actually sounds, I need to look in the image, press to hear the sound, than find in the MIDI where that name is. Finding a note in the pinoo roll is easier visually than looking into the MIDI region for names.
