### ISSUE TITLE
armv7l and aarch64 linux build

### ISSUE THREAD

**Issue by hexdump0815** [x42/avldrums.lv2#17]
i just wanted to let you know that i successfully built avldrums.lv2 on armv7l and aarch64 (ubuntu 18.04) and it works well (tested on both platforms with reaper via carla) ... here are the notes and the patch from my build try: https://github.com/hexdump0815/avldrums-arm-build ... under releases one can find an example build

best wishes and keep up this cool project - hexdump

**Comment by x42** [comment]
Great that you managed to reproduce this.

Yet statically linked armhf and aarch64 builds have been available since over a year already from
https://x42-plugins.com/x42/x42-avldrums

**Comment by x42** [comment]
PS. You don't need to edit the makefile just override the variable when building. e.g.

```
make OPTIMIZATIONS="-O2"
```

**Comment by hexdump0815** [comment]
oh cool - i have overlooked this it seems - i just checked the github releases page ... thanks a lot

**Comment by hexdump0815** [comment]
just verified: your builds work perfectly fine and i saw that you provide all your plugins for arm too - really cool ... time to delete my repo and close this issue then :)

**Comment by x42** [comment]
Well, it's perfectly fine if you want to build it yourself, or add it to a GNU/Linux distro..
