### ISSUE TITLE
License confusion

### ISSUE THREAD

**Issue by krmax44** [x42/avldrums.lv2#19]
The [AVL Drumkits](http://www.bandshed.net/avldrumkits/) site states that it's CC-BY-SA 3.0 licensed, but this repo is GPL-licensed. Which license is relevant to me when I want to use AVL Drums in my own works? Is there a difference to Harrison Mixbus users?

Thanks for your help.

**Comment by x42** [comment]
The repo license is mostly irrelevant, you have to check the header of each source-code file.

The soundfont has a custom CC with exception (see https://github.com/x42/avldrums.lv2/tree/master/sf2). The source-code if GPLv2+(see  https://github.com/x42/avldrums.lv2/blob/master/src/avldrums.c#L3-L16)

**Comment by x42** [comment]
If _"with your own work_" you mean "_music made with it_". Then you can license that music freely. It's all yours.

**Comment by krmax44** [comment]
Awesome, thanks a lot!
