### ISSUE TITLE
exclusive groups on cymbals sound unnatural

### ISSUE THREAD

**Issue by albmef** [x42/avldrums.lv2#25]
Hi !
any way to remove the exclusive group on some of the cymbals ?
i mean a new hit on the crash  1&2, ride shank, .. cuts the trail of the previous hit preventing from playing cymbal rolls.
it works with ride bell or crash 3 though.
is it possible to deactivate it on demand by adding a button, or config file somewhere ? in a future release ?
or is it hardcoded in sf2 ?
if i don't need cymbal chokes i would prefer to have natural souding cymbal hits and rolls
best regards
AM

**Comment by x42** [comment]
The exclusive groups are set into the soundfont itself and not directly available to the synth.
Also this plugin is intentionally kept simple.

For the case you mention, I suggested to use the sfz from http://www.bandshed.net/avldrumkits/ with https://sfz.tools/sfizz/

**Comment by albmef** [comment]
sure ! thanks ;)
