### ISSUE TITLE
Soundfonts questions

### ISSUE THREAD

**Issue by schnitzeltony** [x42/avldrums.lv2#5]
Hi

As 'packager' for embedded devices (currently my main target is Raspi3) I am at avldrums.lv2. In my environment I have already the soundfonts from http://www.bandshed.net/avldrumkits/ and would like to avoid redundancies by just creating some links in avldrums.lv2

Now my questions:
* The fonts shipped here have different size than those from avldrumkits. Are the original ones compatible to those shipped here?
* If yes: In the avldrumkits there are Black_Pearl_4A-1.1.sf2 and Black_Pearl_4B-1.1.sf2. Which one do you suggest?

**Comment by x42** [comment]
I don't know. The files were provided to me by Glen MacArthur. "AVL-Drumkits-1.1-fix-SF2"

**Comment by schnitzeltony** [comment]
So I will try and see what happens :)

**Comment by schnitzeltony** [comment]
Just tested: This is really impressive work you've done. Thanks a lot.

Think I'll drop my idea of linking. For a few megabytes on sdcard I won't make further ado.
