### ISSUE TITLE
You probably forgot to label 0.3.0 as the 'latest' release

### ISSUE THREAD

**Issue by yurivict** [x42/avldrums.lv2#6]
0.3.0 is the actual latest release, but github has 0.2.2 labeled as "latest".

**Comment by x42** [comment]
What do you mean with "label"? Releases are just tags and latest is indeed 0.3.0: https://github.com/x42/avldrums.lv2/releases/tag/v0.3.0

**Comment by yurivict** [comment]
GitHub sometimes labels some older release as "latest". It did this with 0.2.2 2 hours ago, and now there is no "latest" label any more.

**Comment by x42** [comment]
I did a `git push --tags`  but that responded "Everything up-to-date". odd.
