### ISSUE TITLE
This awesome plugin isn't displaying entire GUI from within MuSE 3.0.2

### ISSUE THREAD

**Issue by windowsrefund** [x42/avldrums.lv2#7]
Fresh install of the latest Ubuntu Studio here running MuSE 3.02

MuSE has been compiled with LV2 support enabled and I've been able to view/use a few of them. I'm new to the platform and apps so don't have much experience to go on. However, despite unzipping the latest 64 bit .zip into ~/.lv2, here's what I see when I attempt to "show native gui" from within MuSE

[Screenshot](http://imgur.com/M6uhKjpl.png)

Extending the window borders does not show the missing menus I believe should exist (going by the youtube videos I've watched). Same thing goes for the Red Zepplin Kit. I'm going to reach out to the MuSE side of things as well but am curious what feedback I'll see from this end.

I also ran the muse3 binary with debugging enabled hoping I'd see some clue when firing up the plugin's GUI. Curiously, no error or interesting debug information is output when I take that action.

I will see if I can reproduce this situation in another DAW and will report back.

Thank you

**Comment by windowsrefund** [comment]
Never mind, I now understand that menu (above the kit) is added by Ardour itself.

**Comment by x42** [comment]
The wrong default size is also likely a MUSE or perhaps libsuil issue.  The plugin should scale to fit the window.

**Comment by windowsrefund** [comment]
Thanks for the comment. Here's what I've got over here:

 dpkg -l | grep libsuil
ii  libsuil-0-0:amd64                             0.10.0~dfsg0-1                        amd64        library for loading and wrapping LV2 plugin UIs
